# Production Profile
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

logging.level.root=INFO
logging.level.com.landify=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=ERROR
